import { ReactFullAutoFormInstance } from './ReactFullAutoFormInstance'

// export global autogenerated with defaults
export const globalReactFullAutoFormInstance = new ReactFullAutoFormInstance()
// export class
